# Generated by Django 4.1.3 on 2022-11-06 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_post_reyakks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reyakks',
            field=models.ManyToManyField(blank=True, null=True, related_name='reyakks', to=settings.AUTH_USER_MODEL),
        ),
    ]
