# Generated by Django 4.1.3 on 2022-11-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_reyakks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reyakks',
        ),
    ]
