# Generated by Django 4.1.3 on 2022-11-08 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0006_remove_post_reyakks'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reyakks',
            field=models.ManyToManyField(related_name='reyakks', to=settings.AUTH_USER_MODEL),
        ),
    ]
