# Generated by Django 4.1.3 on 2022-11-09 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0008_remove_post_reyakks'),
        ('post_reyakks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReyakks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reyakker', to='post.post')),
                ('post_reyakker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('post_reyakker', 'post')},
            },
        ),
        migrations.DeleteModel(
            name='Reyakks',
        ),
    ]
